config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :followings, :followers
    end
  end
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any?%>
  <div class="error_explanation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error")%>
    </div>
    <ul class="list-group">
      <%= object.errors.full_messages.each do |message|%>
        <li><%= message%></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any?%>
  <ol class="micropost list-group">
    <%= render @feed_items%>
  </ol>
  <%= paginate @feed_items%>
<%end%>

app/views/shared/_form.html.erb
<%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>

    <%= f.label :name%>
    <%= f.text_field :name, class:"form-control"%>

    <%= f.label :email%>
    <%= f.email_field :email, class:"form-control"%>

    <%= f.label :password%>
    <%= f.password_field :password, class:"form-control"%>

    <%= f.label :password_confirmation%>
    <%= f.password_field :password, class:"form-control"%>

    <%= f.submit yield(:button_text), class:"btn btn-primary"%>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object%>
  <div class="form">
    <%= f.text_area :content, class: "form-control", placeholder: "Compose new micropost..."%>
  </div>
  <div class="custom-file mt-3">
    <%= f.file_field :picture, class:"custom-file-input"%>
    <%= f.label :picture, class:"custom-file-label", accept: 'image/jpeg, image/gif, image/png'%>
  </div>

  <%= f.submit "Post", class: "btn btn-primary w-25 mt-2"%>

<% end %>
<!--画像のファイルサイズに関する警告を出すjQuery-->
<script type="text/javascript">
  $('micropost_picture').bind('change',function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %> <!--プロフィールページでも使うため現在のユーザーを取得しておく-->
<div class="stats">
  <a href="<%= followings_user_path(@user) %>"> <!--followingsとfollowsはRESTfulなインターフェイスではないのでビューヘルパーは使えないのでaタグでリンクを貼る-->
    <strong id="followings" class="stats">
      <%= @user.followings.count %>
    </strong>
    followings
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stats">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), user_path(current_user)%> 
<!--login済みで表示されるviewなのでcurrent_userメソッドでログイン中のユーザーレコードを@current_userに代入する
current_userメソッドのところは実際には@current_user変数で評価されている-->
<h1><%= current_user.name%></h1>
<span><%= link_to "view profile", user_path(current_user)%></span>
<span><%= pluralize(current_user.microposts.count, "micropost")%></span>