config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :followings, :followers
    end
  end
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar">
    <small>
      The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <ul class="list-inline">
        <li class="list-inline-item"><%= link_to "About", about_path %></li>
        <li class="list-inline-item"><%= link_to "Contact", contact_path %></li>
        <li class="list-inline-item"><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-dark bg-dark">
    <%= link_to "sample app", root_path, class:"navbar-brand", id:"logo"%>
    <ul class="list-inline">
      <li class="list-inline-item"><%= link_to "Home",   root_path %></li>
      <li class="list-inline-item"><%= link_to "Help",   help_path %></li>
      <% if logged_in?%>
        <li class= "list-inline-item"><%= link_to "Users", users_path%></li>
        <div class="btn-group">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </button>
          <div class="dropdown-menu dropdown-menu-dark bg-dark">
            <li class="dropdown-item"><%= link_to "Profile", user_path(@current_user)%></li>
            <li class="dropdown-item"><%= link_to "Settings", edit_user_path(@current_user)%></li>
            <li class="dropdown-item"><%= link_to "Log out", logout_path, method: :delete %></li>
          </div>
        </div>
      <% else %>
        <li class="list-inline-item"><%= link_to "Log in", login_path%></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header'%>
    <% flash.each do |message_type, message|%>
      <div class="alert alert-<%= message_type%>"><%= message%></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development?%>
  </body>
</html>